[tool.poetry]
name = "neutone_sdk"
version = "0.1.0"
description = "SDK for wrapping deep learning models for deployment in Neutone"
readme = "README.md"
authors = ["Qosmo <info@qosmo.jp>"]
homepage = "https://github.com/QosmoInc/neutone-sdk.git"
license = "MIT"
packages = [{include = "neutone_sdk"}]
include = ["assets/*"]


[tool.poetry.dependencies]
python = ">=3.8,<3.9"
numpy = "1.22.1"
torch = "1.10.2"
jsonschema = "^4.4.0"
torchinfo = "*"
#librosa = "*"
matplotlib = "*"
pytorch-lightning = "^1.5.10"
SoundFile = "^0.10.3"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
